<a href="https://colab.research.google.com/github/Abimmmm/Pembelajaran-Mesin-2026/blob/main/Week3/Tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [31]:
df = pd.read_csv('wbc.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [6]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [29]:
# 1
# df = df.drop(['id', 'Unnamed: 32'], axis=1)

# X = df.drop('diagnosis', axis=1)
# y = df['diagnosis']

# print("Variabel yang digunakan:")
# print(X.columns.tolist())

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

print("Variabel yang digunakan:")
print(X.columns.tolist())

Variabel yang digunakan:
['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

In [21]:
#  2
df['diagnonis'] = df['diagnosis'].fillna('Unknown')
print("=== Hasil Setelah Fill Nan pada 'diagnosis' ===")
print(df[['diagnosis']].head(33), "\n")
df['diagnosis'] = df['diagnosis'].apply(lambda x: x[0] if x != 'Unknown' else 'U')

le = LabelEncoder()
y = le.fit_transform(y)
print("=== Hasil Setelah Encoding 'diagnosis' ===")
print(dict(zip(le.classes_, le.transform(le.classes_))), "\n")

=== Hasil Setelah Fill Nan pada 'diagnosis' ===
   diagnosis
0          M
1          M
2          M
3          M
4          M
5          M
6          M
7          M
8          M
9          M
10         M
11         M
12         M
13         M
14         M
15         M
16         M
17         M
18         M
19         B
20         B
21         B
22         M
23         M
24         M
25         M
26         M
27         M
28         M
29         M
30         M
31         M
32         M

=== Hasil Setelah Encoding 'diagnosis' ===
{np.int64(0): np.int64(0), np.int64(1): np.int64(1)}

In [24]:
# 3
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
print("=== Hasil Setelah Standarisasi ===")
print(X.head(), "\n")

=== Hasil Setelah Standarisasi ===
   radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466
1     1.829821     -0.353632        1.685955   1.908708        -0.826962
2     1.579888      0.456187        1.566503   1.558884         0.942210
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553
4     1.750297     -1.151816        1.776573   1.826229         0.280372

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          3.283515        2.652874             2.532475       2.217515
1         -0.487072       -0.023846             0.548144       0.001392
2          1.052926        1.363478             2.037231       0.939685
3          3.402909        1.915897             1.451707       2.867383
4          0.539340        1.371011             1.428493      -0.009560

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                2.255747  ...      1.886690      -1.359293         2.303601
1               -0.868652  ...      1.805927      -0.369203         1.535126
2               -0.398008  ...      1.511870      -0.023974         1.347475
3                4.910919  ...     -0.281464       0.133984        -0.249939
4               -0.562450  ...      1.298575      -1.466770         1.338539

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    2.001237          1.307686           2.616665         2.109526
1    1.890489         -0.375612          -0.430444        -0.146749
2    1.456285          0.527407           1.082932         0.854974
3   -0.550021          3.394275           3.893397         1.989588
4    1.220724          0.220556          -0.313395         0.613179

   concave points_worst  symmetry_worst  fractal_dimension_worst
0              2.296076        2.750622                 1.937015
1              1.087084       -0.243890                 0.281190
2              1.955000        1.152255                 0.201391
3              2.175786        6.046041                 4.935010
4              0.729259       -0.868353                -0.397100

[5 rows x 30 columns]

In [25]:
print("=== Hasil Preprocessing (5 baris pertama) ===")
X.head()

=== Hasil Preprocessing (5 baris pertama) ===

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100

In [26]:
# 4
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=0
)

print(f'Jumlah data asli : {X.shape[0]}')
print(f'Jumlah data latih: {X_train.shape[0]}')
print(f'Jumlah data uji  : {X_test.shape[0]}')

print('=========')
print(f'Proporsi label data asli:\n{pd.Series(y).value_counts(normalize=True)}\n')
print(f'Proporsi label data latih:\n{pd.Series(y_train).value_counts(normalize=True)}\n')
print(f'Proporsi label data uji:\n{pd.Series(y_test).value_counts(normalize=True)}')

Jumlah data asli : 569
Jumlah data latih: 455
Jumlah data uji  : 114
=========
Proporsi label data asli:
diagnosis
B    0.627417
M    0.372583
Name: proportion, dtype: float64

Proporsi label data latih:
diagnosis
B    0.626374
M    0.373626
Name: proportion, dtype: float64

Proporsi label data uji:
diagnosis
B    0.631579
M    0.368421
Name: proportion, dtype: float64